version: '3'
services:
    php:
        container_name: php
        build:
            context: ./html
            dockerfile: ../docker/php/Dockerfile
        volumes:
            - ./html:/usr/share/nginx/html:cached
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
        depends_on:
            - db
        restart: always
        tty: true
        privileged: true
        networks:
            - tekko_db_nw
            - tekko_app_nw
    nginx:
        image: nginx:1.14.2-alpine
        container_name: nginx
        ports:
            - "8000:80"
        volumes:
            - ./docker/nginx/http-nginx.conf:/etc/nginx/conf.d/default.conf:cached
            - ./html:/usr/share/nginx/html:cached
            - ./docker/hosts:/etc/hosts:cached
        links:
            - php
            - db
        networks:
            - tekko_app_nw

    db:
        container_name: db
        image: mysql:8.0
        ports:
            - "13306:3306"
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        restart: always
        volumes:
            - ./docker/db/data:/var/lib/mysql
            - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf

        networks:
            - tekko_db_nw
networks:
    tekko_app_nw:
        driver: bridge
    tekko_db_nw:
        driver: bridge
        name: tekko_db_nw